PRO ..ks_event_types

-- drop table ks_event_types purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table ks_event_types (
    id            number        generated by default on null as identity (start with 1) primary key
  , display_seq   number        not null
  , code          varchar2(20)  not null
  , name          varchar2(60)  not null
  , active_ind    varchar2(1)   default 'Y' not null
  , created_by    varchar2(60)  default
                  coalesce(
                     sys_context('APEX$SESSION','app_user')
                     ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     ,sys_context('userenv','session_user')
                     )
                  not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint ks_event_type_u unique (code)
)
enable primary key using index
/

create unique index ks_event_types_u01
  on ks_event_types(upper(code))
/

comment on table ks_event_types is 'Event Type';

comment on column ks_event_types.id is 'surrogate unique identifier';
comment on column ks_event_types.code is  'unchanging unique identifier for the event type';
comment on column ks_event_types.name is  'Friendly name of the event type';
comment on column ks_session_status.display_seq is 'Order for displaying the fav lines';
comment on column ks_session_status.active_ind is 'Is the record enabled Y/N?';

--------------------------------------------------------
--  DDL for Trigger ks_event_types_u_trg
--------------------------------------------------------
create or replace trigger ks_event_types_u_trg
before update
on ks_event_types
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                     sys_context('APEX$SESSION','app_user')
                     ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     ,sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_event_types_u_trg enable;
