create table ks_events (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , name          varchar2(100) not null
  , alias         varchar2(32)
  , location      varchar2(200)
  , begin_date    date          not null
  , end_date      date
  , active_ind    varchar2(1)   not null
  , created_by    varchar2(60) default 
                    coalesce(
                       sys_context('APEX$SESSION','app_user')
                       ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       ,sys_context('userenv','session_user')
                       )
                    not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint ks_events_ck_active
      check (active_ind in ('Y', 'N'))
)
enable primary key using index
/

comment on table ks_events is 'List of Events (ie. Kscope17, ...)';

comment on column ks_events.name is 'Event name';
comment on column ks_events.alias is 'Event short name (if present)';
comment on column ks_events.location is 'Event location (city, state)';
comment on column ks_events.active_ind is 'Is the record enabled Y/N?';
comment on column ks_events.created_by is 'User that created this record';
comment on column ks_events.created_on is 'Date the record was first created';
comment on column ks_events.updated_by is 'User that last modified this record';
comment on column ks_events.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger ks_events_u_trg
--------------------------------------------------------
create or replace trigger ks_events_u_trg
before update
on ks_events
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                     sys_context('APEX$SESSION','app_user')
                     ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     ,sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_events_u_trg enable;
