PRO ..ks_event_admins 

-- drop table ks_event_admins cascade constraints purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table ks_event_admins (
    id              number        generated by default on null as identity (start with 1) primary key not null
  , event_id        number        not null
  , username        varchar2(60)  not null
  , created_by      varchar2(60) default 
                    coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    )
                    not null
  , created_on      date         default sysdate not null
  , updated_by      varchar2(60)
  , updated_on      date
  , constraint ks_event_admins_fk foreign key ( event_id ) references ks_events ( id ) not deferrable
  , constraint ks_event_user_admin_fk foreign key ( username ) references ks_users ( username ) not deferrable
)
enable primary key using index
/

comment on table ks_event_admins is 'List of Event Admins';

comment on column ks_event_admins.id is 'Primary Key ID';
comment on column ks_event_admins.username is 'user with ADMIN role on the event';
comment on column ks_event_admins.created_by is 'User that created this record';
comment on column ks_event_admins.created_on is 'Date the record was first created';
comment on column ks_event_admins.updated_by is 'User that last modified this record';
comment on column ks_event_admins.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--                        123456789012345678901234567890
create or replace trigger ks_event_admins_u_trg
before update
on ks_event_admins
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
