PRO .. ks_email_templates 

-- drop table ks_email_templates cascade constraints purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table ks_email_templates (
    id              number        generated by default on null as identity (start with 1) primary key not null
  , name            varchar2(255) not null
  , template_text   varchar2(4000) not null
  , created_by      varchar2(60) default 
                    coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                    )
                    not null
  , created_on      date         default sysdate not null
  , updated_by      varchar2(60)
  , updated_on      date
)
enable primary key using index
/

comment on table ks_email_templates is 'List Email Templates';

comment on column ks_email_templates.id is 'Primary Key ID';
comment on column ks_email_templates.created_by is 'User that created this record';
comment on column ks_email_templates.created_on is 'Date the record was first created';
comment on column ks_email_templates.updated_by is 'User that last modified this record';
comment on column ks_email_templates.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--                        123456789012345678901234567890
create or replace trigger ks_email_templates_u_trg
before update
on ks_email_templates
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
