PRO ..ks_load_mapping 

-- drop table ks_load_mapping purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table ks_load_mapping (
    id                  number        generated by default on null as identity (start with 1) primary key not null
  , table_name          varchar2(32)   not null
  , display_seq         number         not null
  , header_name         varchar2(4000) not null
  , to_column_name      varchar2(30)
  , created_by          varchar2(60) default on null coalesce(
                           sys_context('APEX$SESSION','app_user')
                         , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                         , sys_context('userenv','session_user')
                        )  not null
  , created_on          date default on null sysdate not null
  , updated_by          varchar2(60)
  , updated_on          date
  , constraint load_mapping_unique unique(table_name,header_name,display_seq)
)
/

comment on table ks_load_mapping is 'Contains a map of which columns in correspond to the export file.';


create or replace trigger ks_load_mapping_bu
  before update on ks_load_mapping
  referencing new as new
  for each row
begin
  :new.updated_on := sysdate;
  if :new.updated_by is null then
    :new.updated_by := coalesce(
          sys_context('APEX$SESSION','app_user')
         ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
         ,sys_context('userenv','session_user')
         );
  end if;
end;
/
