PRO ..ks_roles

-- drop table ks_user_event_track_roles purge;
-- drop table ks_roles purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table ks_roles (
    id            number        generated by default on null as identity (start with 1) primary key
  , display_seq   number        not null
  , role_type     varchar2(10)  not null
  , code          varchar2(20)  not null
  , name          varchar2(32)  not null
  , active_ind    varchar2(1)   not null
  , created_by    varchar2(60) default
                  coalesce(
                     sys_context('APEX$SESSION','app_user')
                     ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     ,sys_context('userenv','session_user')
                     )
                  not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint ks_role_u unique (code)
  , constraint ks_role_types_check check (role_type in ('SELECTION', 'VOTING'))
)
enable primary key using index
/

create unique index ks_roles_u01
  on ks_roles(upper(code))
/

comment on table ks_roles is 'Roles';

comment on column ks_roles.id is 'surrogate unique identifier';
comment on column ks_roles.role_type is  'Role type is either SELECTION | VOTING';
comment on column ks_roles.code is  'unchanging unique identifier for the role';
comment on column ks_roles.name is  'Friendly name of the role';
comment on column ks_session_status.display_seq is 'Order for displaying the fav lines';
comment on column ks_session_status.active_ind is 'Is the record enabled Y/N?';

--------------------------------------------------------
--  DDL for Trigger ks_roles_u_trg
--------------------------------------------------------
create or replace trigger ks_roles_u_trg
before update
on ks_roles
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                     sys_context('APEX$SESSION','app_user')
                     ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     ,sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_roles_u_trg enable;
