create table ks_session_status (
    id            number        generated by default on null as identity (start with 1) primary key not null
  , display_seq   number        not null
  , code          varchar2(20)  not null
  , name          varchar2(32)  not null
  , active_ind    varchar2(1)   not null
  , created_by    varchar2(60) default 
                    coalesce(
                       sys_context('APEX$SESSION','app_user')
                       ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       ,sys_context('userenv','session_user')
                       )
                    not null
  , created_on    date         default sysdate not null
  , updated_by    varchar2(60)
  , updated_on    date
  , constraint ks_session_status_ck_active
      check (active_ind in ('Y', 'N'))
)
enable primary key using index
/

create unique index ks_session_status_u01 on ks_session_status(code);
  
comment on table ks_session_status is 'List of statuses of a session.';

comment on column ks_session_status.display_seq is 'Order for displaying the fav lines';
comment on column ks_session_status.active_ind is 'Is the record enabled Y/N?';
comment on column ks_session_status.created_by is 'User that created this record';
comment on column ks_session_status.created_on is 'Date the record was first created';
comment on column ks_session_status.updated_by is 'User that last modified this record';
comment on column ks_session_status.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger ks_session_status_u_trg
--------------------------------------------------------
create or replace trigger ks_session_status_u_trg
before update
on ks_session_status
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                       sys_context('APEX$SESSION','app_user')
                       ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       ,sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_session_status_u_trg enable;
