
create table ks_session_votes (
    id             number        generated by default on null as identity (start with 1) primary key
  , session_id     number not null
  , session_num    number not null
  , voter          varchar2(500)
  , vote           number
  , comments       varchar2(4000)
  , created_by     varchar2(60) default 
                    coalesce(
                       sys_context('APEX$SESSION','app_user')
                       ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       ,sys_context('userenv','session_user')
                       )
                    not null
  , created_on     date         default sysdate not null
  , updated_by     varchar2(60)
  , updated_on     date
  , constraint ks_sessions_fk foreign key ( session_id ) references ks_sessions ( id )
)
/

comment on table ks_session_votes is 'Event Session votes. One row per voter.';

comment on column ks_session_votes.session_num is 'Unique session identifier assigned by ODTUG. Denormalized include, to make things easy.';
comment on column ks_session_votes.voter is 'Name of individual that casted a vote';
comment on column ks_session_votes.vote is 'Vote rating (1..5)';
comment on column ks_session_votes.created_by is 'User that created this record';
comment on column ks_session_votes.created_on is 'Date the record was first created';
comment on column ks_session_votes.updated_by is 'User that last modified this record';
comment on column ks_session_votes.updated_on is 'Date the record was last modified';

create or replace trigger ks_session_votes_u_trg
before update
on ks_session_votes
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_session_votes_u_trg enable;
