create table ks_tracks (
    id             number        generated by default on null as identity (start with 1) primary key not null
  , display_seq    number        not null
  , name           varchar2(100)  not null
  , alias          varchar2(32)
  , active_ind     varchar2(1)   not null
  , created_by     varchar2(60) default
                    coalesce(
                        sys_context('APEX$SESSION','app_user')
                      , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                      , sys_context('userenv','session_user')
                       )
                    not null
  , created_on     date         default sysdate not null
  , updated_by     varchar2(60)
  , updated_on     date
  , constraint ks_tracks_ck_active
      check (active_ind in ('Y', 'N'))
)
enable primary key using index
/

create unique index ks_tracks_u01 on ks_tracks(upper(name));

comment on table ks_tracks is 'Master (seed) list of tracks used to seed ks_event_tracks';

comment on column ks_tracks.display_seq is 'Order for displaying the lines';
comment on column ks_tracks.active_ind is 'Is the record enabled Y/N?';
comment on column ks_tracks.created_by is 'User that created this record';
comment on column ks_tracks.created_on is 'Date the record was first created';
comment on column ks_tracks.updated_by is 'User that last modified this record';
comment on column ks_tracks.updated_on is 'Date the record was last modified';


--------------------------------------------------------
--  DDL for Trigger ks_tracks_u_trg
--------------------------------------------------------
create or replace trigger ks_tracks_u_trg
before update
on ks_tracks
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                         sys_context('APEX$SESSION','app_user')
                       , regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                       , sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_tracks_u_trg enable;
