PRO ..ks_user_event_track_roles

-- drop table ks_user_event_track_roles purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table ks_user_event_track_roles (
    id                  number        generated by default on null as identity (start with 1) primary key
  , username            varchar2(60) not null
  , event_track_id      number       not null
  , selection_role_code varchar2(20)
  , voting_role_code    varchar2(20)
  , created_by          varchar2(60) default
                        coalesce(
                          sys_context('APEX$SESSION','app_user')
                          ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                          ,sys_context('userenv','session_user')
                          )
                        not null
  , created_on          date         default sysdate not null
  , updated_by          varchar2(60)
  , updated_on          date
  , constraint ks_user_evt_trk_role_user_fk foreign key ( username ) references ks_users ( username ) not deferrable
  , constraint ks_usr_evt_trk_rol_evt_trk_fk foreign key ( event_track_id ) references ks_event_tracks ( id ) not deferrable
  , constraint ks_user_evt_vote_role_role_fk foreign key ( voting_role_code ) references ks_roles ( code ) not deferrable
  , constraint ks_user_evt_vote_sel_role_fk foreign key ( selection_role_code ) references ks_roles ( code ) not deferrable
  , constraint ks_user_evt_trk_role_u1 unique (username, event_track_id)
)
enable primary key using index
/

comment on table ks_user_event_track_roles is 'User Event-Track Roles.';

comment on column ks_user_event_track_roles.id is 'unique surrogate key value ';
comment on column ks_user_event_track_roles.username is 'FK to users table';
comment on column ks_user_event_track_roles.event_track_id is 'FK to event_track table';
comment on column ks_user_event_track_roles.voting_role_code is 'FK to role table for voting role';
comment on column ks_user_event_track_roles.selection_role_code is 'FK to role table for selection role';


--------------------------------------------------------
--                        123456789012345678901234567890
create or replace trigger ks_user_event_track_role_u_trg
before update
on ks_user_event_track_roles
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                     sys_context('APEX$SESSION','app_user')
                     ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     ,sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_user_event_track_role_u_trg enable;
