PRO ..ks_user_evnt_trck_roles 

-- drop table ks_user_evnt_trck_roles cascade constraints purge;

-- Keep table names under 24 characters
--           1234567890123456789012345
create table ks_user_evnt_trck_roles (
    id               number        generated by default on null as identity (start with 1) primary key
  , user_id          number not null
  , event_track_id   number not null
  , role_id          number not null
  , created_by       varchar2(60) default
                     coalesce(
                        sys_context('APEX$SESSION','app_user')
                        ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                        ,sys_context('userenv','session_user')
                        )
                     not null
  , created_on       date         default sysdate not null
  , updated_by       varchar2(60)
  , updated_on       date
  , constraint ks_user_evt_trk_role_user_fk foreign key ( user_id ) references ks_users ( id ) not deferrable;
  , constraint ks_usr_evt_trk_rol_evt_trk_fk foreign key ( event_track_id ) references ks_event_tracks ( id ) not deferrable;
  , constraint ks_user_evt_trk_role_role_fk foreign key ( role_id ) references ks_user_evnt_trck_roles ( id ) not deferrable;
)
enable primary key using index
/

comment on table ks_user_evnt_trck_roles is 'User Event-Track Roles.';

comment on column ks_user_evnt_trck_roles.id is 'unique surrogate key value ';
comment on column ks_user_evnt_trck_roles.user_id is 'FK to users table';
comment on column ks_user_evnt_trck_roles.event_track_id is 'FK to event_track table';
comment on column ks_user_evnt_trck_roles.role_id is 'FK to role table';


--------------------------------------------------------
--                        123456789012345678901234567890
create or replace trigger ks_user_evnt_trck_roles_u_trg
before update
on ks_user_evnt_trck_roles
referencing old as old new as new
for each row
begin
  :new.updated_on := sysdate;
  :new.updated_by := coalesce(
                     sys_context('APEX$SESSION','app_user')
                     ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
                     ,sys_context('userenv','session_user')
                     );
end;
/
alter trigger ks_user_evnt_trck_roles_u_trg enable;
